#
###################################
# Site wide configuration
####################################
#
title: Ankit Yadav
email: connectankityadav@gmail.com
description: Personal Blog of Ankit Yadav (@yadavankit)
url:


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Kolkata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: ankit yadav
  avatar: logo.png
  job: "Learner for life"
  bio: "Entrepreneur, Pythonista, Djangonaut, iOS, IBM Watson Dev, AI Research Freak who prefers Tea to Coffee"
  email: connectankityadav@gmail.com
  disqus-shortname: yadavankit
  twitter: theyadavankit
  facebook: techjunkie007
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  gitlab: #username
  stackoverflow: 4990064/ankit-yadav
  linkedin: connectankityadav
  skype: #username
  xing: #username
  instagram: techjunkie
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
